# Lint as: python2, python3
"""MT model hyper-parameters.

All MT modules defining ModelParams should be imported here.
"""

# Import ModelParams to ensure that they are added to the global registry.
# pylint: disable=unused-import
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_de_bnmtv15
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_de_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_es_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_fr_bnmtv15
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_fr_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_fr_bnmtv25
import google3.learning.brain.research.babelfish.mt.params.canonical.prod.en_fr_transformer
import google3.learning.brain.research.babelfish.mt.params.nmt_multi_config
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_bnmtv15
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_bnmtv25
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_ensemble
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_hybrid
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_memory
import google3.learning.brain.research.babelfish.mt.params.prod.versioned_transformer
import google3.learning.brain.research.babelfish.mt.params.qe.ewok_ratings.en_de_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.ewok_ratings.en_es_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.ewok_ratings.en_id_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.ewok_ratings.en_it_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.ewok_ratings.en_ro_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.localization.quasi_mt
import google3.learning.brain.research.babelfish.mt.params.qe.localization.quasiMT_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.localization.quasiMT_en_de
import google3.learning.brain.research.babelfish.mt.params.qe.localization.quasiMT_en_de_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.localization.quasiMT_en_zh_local
import google3.learning.brain.research.babelfish.mt.params.qe.newton.en_id_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.web_clean_ewok_perfect.en_es_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.wmt09_17_newstest.de_en
import google3.learning.brain.research.babelfish.mt.params.qe.wmt09_17_newstest.en_de
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.de_en
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.de_en_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.en_de
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.en_de_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.quasiMT_de_en_classifier
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.quasiMT_en_de
import google3.learning.brain.research.babelfish.mt.params.qe.wmt17.quasiMT_en_de_classifier
import google3.learning.brain.research.babelfish.mt.params.research.ape.en_en_naturalize
import google3.learning.brain.research.babelfish.mt.params.research.curriculum.paracrawl16_en_fr
import google3.learning.brain.research.babelfish.mt.params.research.discomt.es
import google3.learning.brain.research.babelfish.mt.params.research.document.de_en
import google3.learning.brain.research.babelfish.mt.params.research.embedded.en_es_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.en_es_spoken_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.en_fr_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.en_fr_hybrid
import google3.learning.brain.research.babelfish.mt.params.research.embedded.en_fr_transformer
import google3.learning.brain.research.babelfish.mt.params.research.embedded.en_zh_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.es_en_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.fr_en_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.multilingual_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.embedded.zh_en_bnmtv2
import google3.learning.brain.research.babelfish.mt.params.research.ensemble.wmt14_en_fr
import google3.learning.brain.research.babelfish.mt.params.research.gender_in_context.contextual_rewriter_es_en
import google3.learning.brain.research.babelfish.mt.params.research.gender_in_context.en_es
import google3.learning.brain.research.babelfish.mt.params.research.gender_in_context.es_en
import google3.learning.brain.research.babelfish.mt.params.research.i18n.asst_iql_seq2seq
import google3.learning.brain.research.babelfish.mt.params.research.i18n.canonical
import google3.learning.brain.research.babelfish.mt.params.research.i18n.canonical_argument
import google3.learning.brain.research.babelfish.mt.params.research.i18n.canonical_joint_parsing
import google3.learning.brain.research.babelfish.mt.params.research.i18n.clic
import google3.learning.brain.research.babelfish.mt.params.research.i18n.deenesfrpt_deenesfrpt
import google3.learning.brain.research.babelfish.mt.params.research.i18n.mldoc
import google3.learning.brain.research.babelfish.mt.params.research.i18n.sos_suicide
import google3.learning.brain.research.babelfish.mt.params.research.i18n.symptom_search
import google3.learning.brain.research.babelfish.mt.params.research.i18n.xnli
import google3.learning.brain.research.babelfish.mt.params.research.iwslt17.deen_deen
import google3.learning.brain.research.babelfish.mt.params.research.iwslt17.deenitnlro_deenitnlro
import google3.learning.brain.research.babelfish.mt.params.research.iwslt17.deenitnlro_deenitnlro_multitask
import google3.learning.brain.research.babelfish.mt.params.research.iwslt17.en_de
import google3.learning.brain.research.babelfish.mt.params.research.joint_semantic_parsing.atis
import google3.learning.brain.research.babelfish.mt.params.research.m4.public.bilingual_baselines
import google3.learning.brain.research.babelfish.mt.params.research.m4.public.multilingual_baselines
import google3.learning.brain.research.babelfish.mt.params.research.memory.kg_entity
import google3.learning.brain.research.babelfish.mt.params.research.meta_learning.wmt14_en_fr
import google3.learning.brain.research.babelfish.mt.params.research.meta_learning.wmt14_en_fr_wmt18_en_de
import google3.learning.brain.research.babelfish.mt.params.research.meta_learning.wmt18_en_de
import google3.learning.brain.research.babelfish.mt.params.research.misc.bd_spoken
import google3.learning.brain.research.babelfish.mt.params.research.misc.df_pilot_en_fr
import google3.learning.brain.research.babelfish.mt.params.research.misc.europarl_fr_en
import google3.learning.brain.research.babelfish.mt.params.research.misc.gender_rewriter
import google3.learning.brain.research.babelfish.mt.params.research.misc.pragma_x
import google3.learning.brain.research.babelfish.mt.params.research.misc.pragma_x_salient_terms
import google3.learning.brain.research.babelfish.mt.params.research.misc.text_norm
import google3.learning.brain.research.babelfish.mt.params.research.misc.un_spa_eng
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.en_de
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.en_zh
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.fr_de
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.fr_en
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.multilingual
import google3.learning.brain.research.babelfish.mt.params.research.module_sharing.zh_en
import google3.learning.brain.research.babelfish.mt.params.research.multisource.versioned_multisource
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.de_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.en_de
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.en_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.fil_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.fr_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.hybrid_base
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.id_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.ja_en
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.ja_fr
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.ja_ko
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.ja_zh
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.ko_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.mass_base
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.multi_20_20
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.multi_20_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.multi_ja_20
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.th_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.transformer_base
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.vi_ja
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.wmt_en_de_mass
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.wmt_en_fr_mass
import google3.learning.brain.research.babelfish.mt.params.research.olympics2020.zh_ja
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.all_all
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.baselines
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_bilingual
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_multilingual
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_multilingual_gpipe
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_multilingual_mass
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_multilingual_moe
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_ntl
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_pretraining
import google3.learning.brain.research.babelfish.mt.params.research.one_hundred_langs.m4_prod
import google3.learning.brain.research.babelfish.mt.params.research.pathways.wmt14
import google3.learning.brain.research.babelfish.mt.params.research.prod.csdeenesfrruzh_csdeenesfrruzh
import google3.learning.brain.research.babelfish.mt.params.research.prod.de_en
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_ar
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_de
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_es
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_hi
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_vi
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_zh
import google3.learning.brain.research.babelfish.mt.params.research.prod.en_zh_distill
import google3.learning.brain.research.babelfish.mt.params.research.prod.endefrjakoptes_endefrjakoptes
import google3.learning.brain.research.babelfish.mt.params.research.prod.enes_enes
import google3.learning.brain.research.babelfish.mt.params.research.prod.es_en
import google3.learning.brain.research.babelfish.mt.params.research.prod.headroom_ende
import google3.learning.brain.research.babelfish.mt.params.research.prod.interindic_en
import google3.learning.brain.research.babelfish.mt.params.research.prod.tr_en
import google3.learning.brain.research.babelfish.mt.params.research.prod.zh_en
import google3.learning.brain.research.babelfish.mt.params.research.prod.zh_en_distill
import google3.learning.brain.research.babelfish.mt.params.research.qi18_ted_talks.all_all
import google3.learning.brain.research.babelfish.mt.params.research.qi18_ted_talks.all_en
import google3.learning.brain.research.babelfish.mt.params.research.qi18_ted_talks.en_all
import google3.learning.brain.research.babelfish.mt.params.research.robustness.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.robustness.ja_en
import google3.learning.brain.research.babelfish.mt.params.research.sentence_explorer.en
import google3.learning.brain.research.babelfish.mt.params.research.sentence_explorer.i18n
import google3.learning.brain.research.babelfish.mt.params.research.sentence_explorer.ondevice
import google3.learning.brain.research.babelfish.mt.params.research.sequence_tagging.atis
import google3.learning.brain.research.babelfish.mt.params.research.text_classification.atis
import google3.learning.brain.research.babelfish.mt.params.research.tfx.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.uncorpus.arenesfrruzh
import google3.learning.brain.research.babelfish.mt.params.research.unsup_mt.en_de
import google3.learning.brain.research.babelfish.mt.params.research.unsup_mt.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.wmt13.es_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.char_en_de
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.char_en_fr
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.deenfr_deenfr
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.defr_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.en_de
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.en_defr
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.en_fr
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.en_fr_bt
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.en_fr_cds_tags
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.en_fr_en_ape
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.fr_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt14.wmt_enfr_esn_custom_H
import google3.learning.brain.research.babelfish.mt.params.research.wmt15.char_cs_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt15.char_de_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt15.char_fi_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt15.en_de
import google3.learning.brain.research.babelfish.mt.params.research.wmt15.enfr_enfr
import google3.learning.brain.research.babelfish.mt.params.research.wmt16.en_ro
import google3.learning.brain.research.babelfish.mt.params.research.wmt16.en_ro_en_ape
import google3.learning.brain.research.babelfish.mt.params.research.wmt16.ro_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt16_captions.char_de_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt17.en_de
import google3.learning.brain.research.babelfish.mt.params.research.wmt17.zh_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt18.de_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt18.en_de
import google3.learning.brain.research.babelfish.mt.params.research.wmt18.en_de_back_fwd_tr
import google3.learning.brain.research.babelfish.mt.params.research.wmt18.en_de_en_ape
import google3.learning.brain.research.babelfish.mt.params.research.wmt19.de_en
import google3.learning.brain.research.babelfish.mt.params.research.wmt19.en_de
